import manifest from "./logo-manifest.json";

/**
 * Build-time logo manifest (generated by scripts/generate-logo-manifest.mjs from
 * the files in public/business-lines/). Keys are slug-exact, lowercased file base
 * names; values are public URLs. Resolution is DETERMINISTIC and computed server
 * side — there is no render-time `onError` 404 fallback chain, so logos never
 * flicker or cross-map. A business line resolves iff a file named exactly
 * `<slug>.<ext>` exists (ext priority: svg → png → webp → jpg → jpeg).
 */
const LOGO_MANIFEST = manifest as Record<string, string>;

/** Pure slug-exact resolver (case-insensitive); null when the slug has no file. */
export function resolveLineLogo(
  map: Record<string, string>,
  slug: string,
): string | null {
  return map[slug.toLowerCase()] ?? null;
}

/** Slug-exact logo URL for a business line, or null when no file exists. */
export function lineLogoSrc(slug: string): string | null {
  return resolveLineLogo(LOGO_MANIFEST, slug);
}

/** slug → src map for a set of business-line slugs (only the resolved ones). */
export function lineLogoMap(slugs: string[]): Record<string, string> {
  const out: Record<string, string> = {};
  for (const slug of slugs) {
    const src = resolveLineLogo(LOGO_MANIFEST, slug);
    if (src) out[slug] = src;
  }
  return out;
}
